

package fr.insset.jeanluc.constraint_language;

import static fr.insset.jeanluc.constraint_language.Util.readFile;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Map;

/**
 * Reads a token file as generated by antlr4 and returns a map
 * &lt;Integer, String&gt;
 *
 * @author jldeleage
 */
public class TokenReader {


    public Map<Integer, String> read(String inFilePath) throws FileNotFoundException {
        String readFile = readFile(inFilePath);
        String[]   lines = readFile.split("\n");
        for (String aLine : lines) {
            if (aLine.length() <= 3) {
                break;
            }
            int index = aLine.indexOf('=');
            String  value = aLine.substring(0, index);
            String keyAsString   = aLine.substring(index + 1);
            // We don't need to keep track of the actual values but of the
            // symbols only
            if (value.startsWith("'")) {
                continue;
            }
            int    key   = Integer.parseInt(keyAsString);
            symbols.put(key, value);
        }
        return symbols;
    }

    private Map<Integer, String>        symbols = new HashMap<>();

}
